stages:
  prepare:
    cmd: python src/data/del_dt.py
    deps:
    - data/raw/raw.csv
    - src/data/del_dt.py
    outs:
    - data/processed/raw_cleaned.csv
  split:
    cmd: python src/data/split_data.py
    deps:
    - data/processed/raw_cleaned.csv
    - src/data/split_data.py
    outs:
    - data/split/X_test.csv
    - data/split/X_train.csv
    - data/split/y_test.csv
    - data/split/y_train.csv
  normalize:
    cmd: python src/features/normalize_data.py
    deps:
    - data/split/X_test.csv
    - data/split/X_train.csv
    - src/features/normalize_data.py
    outs:
    - data/normalized/X_test_scaled.csv
    - data/normalized/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid_search_model.py
    deps:
    - data/normalized/X_train_scaled.csv
    - data/split/y_train.csv
    - params.yaml
    - src/models/grid_search_model.py
    outs:
    - models/best_params.pkl
